version: '2.4'

services:
  posterr:
    image: posterr
    container_name: posterr
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: "Australia/Brisbane"
      NODE_ENV: production
      BASEPATH: ""
    volumes:
      - /c/docker/posterr/randomthemes:/usr/src/app/public/randomthemes
      - /c/docker/posterr/config:/usr/src/app/config
    ports:
      - 9876:3000

